name: Tests

on:
  push:
    branches:
      - main
      - master
      - develop
      - dev/*
  pull_request:
    branches:
      - main
      - master
      - develop
      - dev/*

jobs:
  call-tests:
    name: Extension tests
    uses: phpbb-extensions/test-framework/.github/workflows/tests.yml@3.3.x
    with:
      EXTNAME: sebo/postreact
      PHPBB_BRANCH: '3.3.x'
      PRIMARY_PHP_VERSION: '7.2'
      PHP_VERSION_MATRIX: '["7.2", "7.3", "7.4"]'